spring:
  datasource:
    username: dialog_service
    url: jdbc:postgresql://localhost:5777/dialog
    password: dialog_password

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_1