spring:
  application:
    name: social_net_otus
  flyway:
    #    baseline-on-migrate: true
    default-schema: ${db.schema}
    locations: "classpath:db/migrations"
  datasource:
    url:
    username:
    password:
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    url: "/openapi.yml"
  show-actuator: true


db:
  schema:

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
#      exposure:

  endpoints:
    web:
      exposure:
        include: "*"
