spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: github-client-id
#            clientSecret: github-client-secret
  application:
    name: social_net_otus
  flyway:
    #    baseline-on-migrate: true
    default-schema: ${db.schema}
    locations: "classpath:db/migrations"
  datasource:
    url:
    username:
    password:
db:
  schema: