spring:
  application:
    name: social_net_otus

  datasource:
    master:
      username: "postgres"
      url: jdbc:postgresql://localhost:5888/social_net_otus?currentSchema=${db.schema}
      password: "Password1"
      hikari:
        connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${db.schema}
    replicas:
      -  url: jdbc:postgresql://localhost:5889/social_net_otus?currentSchema=${db.schema}
         username: "postgres"
         password: "Password1"
      -  url: jdbc:postgresql://localhost:5890/social_net_otus?currentSchema=${db.schema}
         username: "postgres"
         password: "Password1"
db:
  schema: social_net_otus
#
#logging:
#  level:
#    sql: debug

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem