spring:
  application:
    name: social_net_otus
  flyway:
    #    baseline-on-migrate: true
    default-schema: ${db.schema}
    locations: "classpath:db/migrations"
  datasource:
        username:
        url:
        password:
        hikari:
          connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${db.schema}
#    master:
#      username:
#      url:
#      password:
#      hikari:
#        connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${db.schema}
#    replicas:
#      - url:
#        username:
#        password:
#      - url:
#        username:
#        password:


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    url: "/openapi.yml"
  show-actuator: true


db:
  schema:

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
#      exposure:

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    enable:
      jvm: true
      jdbc: true
      web: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
