{
 "title": "Spring Boot Application Monitoring",
 "description": "Дашборд для мониторинга Spring Boot приложения",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"\"}[5m])) * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", container_name!=\"\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{image!=\"\", container_name!=\"\"}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(jvm_thread_states_thread_count{state=\"RUNNABLE\"})"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"\"}[5m])max(jvm_memory_heap_usage_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\", container_name!=\"\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\", container_name!=\"\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Write Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{image!=\"\", container_name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{image!=\"\", container_name!=\"\"}[5m]))"
    }
   ]
  }
 ]
}