spring:
  application:
    name: social_net_otus

  datasource:
    url: jdbc:postgresql://social_net_otus_db:5432/social_net_otus?currentSchema=${db.schema}
    username: "postgres"
    password: "Password1"
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${db.schema}

rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    url: "/openapi.yml"

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    enable:
      jvm: true
      jdbc: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus