spring:
  application:
    name: dialogs
  datasource:
    username: dialog_service
    url: jdbc:postgresql://citus-coordinator:5432/dialog?currentSchema=${db.schema}
    password: dialog_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${db.schema};
  flyway:
    default-schema: ${db.schema}
    locations: "classpath:db/migrations"
  devtools:
    add-properties: false
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: group_1
db:
  schema: dialogs
#logging:
#  level:
#    root: debug
app:
  sharding:
    total-shards: 32
    default-shard: 0
    datasource: