version: "3.9"



x-etcd-base: &etcd-base
  image: quay.io/coreos/etcd:v3.5.18
  entrypoint: /usr/local/bin/etcd
  networks:
    - otus_highload
  volumes:
    - etcd-data:/etcd-data
  restart: unless-stopped
  environment:
    ETCD_DATA_DIR: /etcd-data
    ETCD_INITIAL_CLUSTER_STATE: "new"
    ETCD_INITIAL_CLUSTER_TOKEN: "my_secret_token"
    ETCD_ENABLE_V2: "true"
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"



services:

  social_net_otus:
    container_name: socialnetotus
    build:
      context: ..
    restart: always
    ports:
      - 9081:8080
    depends_on:
#      - social_net_otus_db
      - haproxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      db.schema: social_net_otus
    healthcheck:
      test: [ "CMD", "wget http://localhost:8080/actuator/health | grep UP" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    volumes:
      - "./application-docker.yml:/opt/social_net_otus/application.yml"
    networks:
      - otus_highload

#  ab_tester:
#    container_name: ab_tester
#    build:
#      context: ./Ab
#    ports:
#      - "8888:8888"
#    depends_on:
#      - social_net_otus
#    networks:
#      - otus_highload

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Конфигурационный файл
      - prometheus_data:/prometheus  # Volume для данных
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Указание конфигурационного файла
    ports:
      - "9090:9090"  # Проброс порта
    networks:
      - otus_highload

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3020:3000"
    networks:
      - otus_highload

  etcd:
    image: quay.io/coreos/etcd:v3.5.18
    container_name: etcd
    entrypoint: /usr/local/bin/etcd
    networks:
      - otus_highload
    restart: unless-stopped
    environment:
      ETCD_NAME: etcd
      ETCD_DATA_DIR: /etcd-data
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: my_secret_token
      ETCD_ENABLE_V2: "true"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380,etcd01=http://etcd01:2380,etcd02=http://etcd02:2380
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m


  etcd01:
    image: quay.io/coreos/etcd:v3.5.18
    container_name: etcd01
    entrypoint: /usr/local/bin/etcd
    networks:
      - otus_highload
    restart: unless-stopped
    environment:
      ETCD_NAME: etcd01
      ETCD_DATA_DIR: /etcd-data
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: my_secret_token
      ETCD_ENABLE_V2: "true"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd01:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd01:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380,etcd01=http://etcd01:2380,etcd02=http://etcd02:2380
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m

  etcd02:
    image: quay.io/coreos/etcd:v3.5.18
    container_name: etcd02
    entrypoint: /usr/local/bin/etcd
    networks:
      - otus_highload
    restart: unless-stopped
    environment:
      ETCD_NAME: etcd02
      ETCD_DATA_DIR: /etcd-data
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: my_secret_token
      ETCD_ENABLE_V2: "true"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd02:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd02:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380,etcd01=http://etcd01:2380,etcd02=http://etcd02:2380
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m

  patroni: &patroni-base
    container_name: patroni
    image: ghcr.io/batonogov/patroni-docker:v4.0.4-pg17.3
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: unless-stopped
    user: postgres
    volumes:
      - patroni-data:/var/lib/postgres/patroni/main
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - tmp-pgpass:/tmp
      - ./backup.sql:/dump.sql

    environment:
      PATRONI_API_CONNECT_PORT: 8008
      REPLICATION_NAME: replicator
      REPLICATION_PASS: replpass
      SU_NAME: postgres
      SU_PASS: Password1
      POSTGRES_APP_ROLE_PASS: appass

    networks:
      - otus_highload
    depends_on:
      - etcd
      - etcd01
      - etcd02
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m

  patroni1:
    <<: *patroni-base
    container_name: patroni1
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - patroni-data1:/var/lib/patroni/main

  patroni2:
    <<: *patroni-base
    container_name: patroni2
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - patroni-data2:/var/lib/patroni/main


  haproxy:
    image: haproxy:3.1.3-alpine
    container_name: haproxy
    user: root
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 5445:5432
      - 8181:8080
    restart: unless-stopped
    networks:
      - otus_highload
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64m

networks:
  otus_highload:
    driver: bridge

volumes:
  social_net_otus:
    external: false
  grafana:
      external: false
  prometheus_data:
      external: false
  prometheus:
    external: false
  etcd-data:
    external: false

  patroni-data:
    external: false
  patroni-data1:
    external: false
  patroni-data2:
    external: false
  tmp-pgpass:
    external: false

    #  patroni-master:
    #    external: false
    #  etcd_data:
    #    external: false
    #  social_net_otus_db_slave1:
    #    external: false
    #  social_net_otus_db_slave2:
    #    external: false




    #
    #  etcd0:
    #    <<: *etcd-base
    #    container_name: etcd0
    #    environment:
    #      ETCD_NAME: etcd0
    #      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd0:2380"
    #      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd0:2379"
    #      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
    #
    #  etcd1:
    #    <<: *etcd-base
    #    container_name: etcd1
    #    environment:
    #      ETCD_NAME: etcd1
    #      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
    #      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
    #      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
    #
    #  etcd2:
    #    <<: *etcd-base
    #    container_name: etcd2
    #    environment:
    #      ETCD_NAME: etcd2
    #      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
    #      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
    #      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"