global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'socialnetapp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['socialnetotus:8080']

  - job_name: 'patroni'
    static_configs:
      - targets:
          - 'patroni:8008'
          - 'patroni1:8008'
          - 'patroni2:8008'

  - job_name: 'etcd'
    static_configs:
      - targets:
          - 'etcd0:2379'
          - 'etcd1:2379'
          - 'etcd2:2379'