version: '3.9'

x-etcd-base: &etcd-base
  image: quay.io/coreos/etcd:v3.5.18
  entrypoint: /usr/local/bin/etcd
  networks:
    - otus_highload
  restart: unless-stopped
  environment:
    ETCD_NAME: etcd
    ETCD_DATA_DIR: /etcd-data
    ETCD_INITIAL_CLUSTER_STATE: "new"
    ETCD_INITIAL_CLUSTER_TOKEN: "my_secret_token"
    ETCD_ENABLE_V2: "true"
    ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"

services:
  etcd0:
    <<: *etcd-base
    environment:
      ETCD_NAME: etcd0
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd0:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd0:2379"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"

  etcd1:
    <<: *etcd-base
    environment:
      ETCD_NAME: etcd1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"

  etcd2:
    <<: *etcd-base
    environment:
      ETCD_NAME: etcd2
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"

  patroni: &patroni-base
    image: ghcr.io/batonogov/patroni-docker:v4.0.4-pg17.3
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: unless-stopped
    user: "999:999"
    volumes:
      - patroni-data:/var/lib/postgresql/patroni/main
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - tmp-pgpass:/tmp
    environment:
      PATRONI_API_CONNECT_PORT: 8008
      REPLICATION_NAME: replicator
      REPLICATION_PASS: replpass
      SU_NAME: postgres
      SU_PASS: example
      POSTGRES_APP_ROLE_PASS: appass
    networks:
      - otus_highload
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m

  patroni1:
    <<: *patroni-base
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - patroni-data1:/var/lib/postgresql/patroni/main

  patroni2:
    <<: *patroni-base
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - patroni-data2:/var/lib/postgresql/patroni/main

  haproxy:
    image: haproxy:3.1.3-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 5445:5432
      - 8181:8080
    restart: unless-stopped
    networks:
      - otus_highload
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64m


networks:
  otus_highload:
    driver: bridge

volumes:
  patroni-data:
    external: false
  patroni-data1:
    external: false
  patroni-data2:
    external: false
  tmp-pgpass:
    external: false
